-- =========================================
-- CONCERT TICKET DATABASE
-- =========================================


-- =========================================
-- USERS
-- =========================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    phone VARCHAR(30),

    role VARCHAR(20) NOT NULL DEFAULT 'customer'
        CHECK (role IN ('admin', 'customer')),

    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- ARTISTS
-- =========================================

CREATE TABLE artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    photo TEXT,

    description TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================
-- EVENTS
-- =========================================

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    artist_id BIGINT NOT NULL,

    title VARCHAR(255) NOT NULL,

    description TEXT NOT NULL,

    location VARCHAR(255) NOT NULL,

    event_date TIMESTAMPTZ NOT NULL,

    poster TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'closed')),

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_event_artist
        FOREIGN KEY (artist_id)
        REFERENCES artists(id)
        ON DELETE RESTRICT
);


-- =========================================
-- TICKET CATEGORIES
-- =========================================

CREATE TABLE ticket_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL,

    category_name VARCHAR(100) NOT NULL,

    price DECIMAL(14, 2) NOT NULL
        CHECK (price > 0),

    quota INTEGER NOT NULL
        CHECK (quota > 0),

    remaining INTEGER NOT NULL
        CHECK (
            remaining >= 0
            AND remaining <= quota
        ),

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_ticket_event
        FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);


-- =========================================
-- ORDERS
-- =========================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    order_code VARCHAR(100) NOT NULL UNIQUE,

    total DECIMAL(14, 2) NOT NULL
        CHECK (total >= 0),

    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'paid',
                'rejected',
                'cancelled'
            )
        ),

    qr_code TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
);


-- =========================================
-- ORDER ITEMS
-- =========================================

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    ticket_category_id BIGINT NOT NULL,

    qty INTEGER NOT NULL
        CHECK (qty > 0),

    subtotal DECIMAL(14, 2) NOT NULL
        CHECK (subtotal >= 0),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_item_ticket
        FOREIGN KEY (ticket_category_id)
        REFERENCES ticket_categories(id)
        ON DELETE RESTRICT
);


-- =========================================
-- PAYMENTS
-- =========================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL UNIQUE,

    payment_method VARCHAR(100) NOT NULL,

    proof_image TEXT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'approved',
                'rejected'
            )
        ),

    verified_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
);


-- =========================================
-- INDEX
-- =========================================

CREATE INDEX idx_events_artist_id
ON events(artist_id);


CREATE INDEX idx_ticket_categories_event_id
ON ticket_categories(event_id);


CREATE INDEX idx_orders_user_id
ON orders(user_id);


CREATE INDEX idx_orders_status
ON orders(status);


CREATE INDEX idx_order_items_order_id
ON order_items(order_id);


CREATE INDEX idx_payments_order_id
ON payments(order_id);